### ISSUE TITLE
question: editing existing files planned?

### ISSUE THREAD

**Issue by kevinmatthes** [jmcnamara/rust_xlsxwriter#10]
### Question

Hello!

I have got a question concerning both the roadmap (#1) and the README of this project.  The README states that editing existing files is not supported, yet.  The roadmap does not mention whether such a feature would be scheduled for future releases.

Thus, I was wondering whether editing existing files is planned or if such functionalities would be beyond this project's scope.

**Comment by jmcnamara** [comment]
Hello and thanks for the question.

I have no plans to support reading/modifying existing files. My focus is on creating a robust featureful library for writing Excel files. Reading/modifying is just too big a secondary task.
