### ISSUE TITLE
Bug: wrong date in changelog

### ISSUE THREAD

**Issue by CMelz** [jmcnamara/rust_xlsxwriter#101]
### Current behavior

The latest changelog is titled "[0.71.0] - 2023-07-20".

### Expected behavior

It was actually updated at 2024-07-20.

### Sample code to reproduce

```rust
fn main() {}
```
```


### Environment

_No response_

### Any other information

_No response_

**Comment by jmcnamara** [comment]
Thanks. All the dates for this year were wrong. Weird :-|

Fixed on main. Thanks.
