### ISSUE TITLE
feature request: autofit

### ISSUE THREAD

**Issue by Zerowalker** [jmcnamara/rust_xlsxwriter#102]
### Feature Request

The ability to auto size the column/row sizes to it's content.

**Comment by jmcnamara** [comment]
Thanks for the suggestion.

`rust_xlsxwriter` already supports column autofit via [Worksheet::autofit()](https://docs.rs/rust_xlsxwriter/latest/rust_xlsxwriter/worksheet/struct.Worksheet.html#method.autofit).

Could you give some more detail about what you are requesting.

**Comment by Zerowalker** [comment]
Oh i was confusing this with `xlsxwriter`, sorry!
Can probably just change to using this in my project then:)
