### ISSUE TITLE
feature request: setting print settings

### ISSUE THREAD

**Issue by Expurple** [jmcnamara/rust_xlsxwriter#104]
### Feature Request

Recently, I needed to set print settings. In particular, landscape page orientation and fit-to-width. Apparently, this isn't even on the roadmap. I had to resort to saving the file and then editing it with [umya_spreadsheet](https://docs.rs/umya-spreadsheet/latest/umya_spreadsheet), which [supports](https://docs.rs/umya-spreadsheet/2.0.1/umya_spreadsheet/structs/struct.PageSetup.html) this.

Thanks for this great library, by the way. I prefer your API and docs.

**Comment by jmcnamara** [comment]
It is on the road map as "Worksheet page setup functions", and it is already completed: [Page setup options](https://rustxlsxwriter.github.io/worksheet/page_setup.html). 🙂

**Comment by Expurple** [comment]
Haha, apparently I made some very unlucky searches on docs.rs:
- [orientation](https://docs.rs/rust_xlsxwriter/latest/rust_xlsxwriter/?search=orientation)
- [width](https://docs.rs/rust_xlsxwriter/latest/rust_xlsxwriter/?search=width)

Thank you.
