### ISSUE TITLE
Feature Request: Ability to switch between regex and regex_lite crates

### ISSUE THREAD

**Issue by Degubi** [jmcnamara/rust_xlsxwriter#105]
### Feature Request

The 'regex' crate is huge, and there exists the crate 'regex_lite' that is much smaller & faster to compile, but with the tradeoff of being slower at runtime.
Would it be possible to add a feature flag to be able to switch between the 2 dependencies?

**Comment by jmcnamara** [comment]
Thanks for the suggestion. I'll look into it.

**Comment by Degubi** [comment]
Hi!
I've already implemented locally, running tests atm.
Would you take a look? I'll create a pr soon.
Have a nice day!

**Comment by jmcnamara** [comment]
> Would you take a look?

Sure. Create a PR and I'll take a look. No rush since I will be offline until the end of the week.

**Comment by Degubi** [comment]
Opened #106

**Comment by jmcnamara** [comment]
Closing the feature request as "Can't fix" due to the lack of Unicode support in `regex-lite`. See the discussion in #106.
