### ISSUE TITLE
question: No two saves produce identical output

### ISSUE THREAD

**Issue by arifd** [jmcnamara/rust_xlsxwriter#107]
### Question

This makes me not be able to write a test and compare against a previously saved truth.

I suspect it just contains a timestamp or something, is there a way to make two saves be bitwise reproducible?

Btw, thanks for this wonderful contribution to the Rust ecosystem!!

**Comment by jmcnamara** [comment]
Thanks for the feedback. 

That issue and the workaround is explained in the docs: https://docs.rs/rust_xlsxwriter/latest/rust_xlsxwriter/workbook/index.html#checksum-of-a-saved-file

**Comment by arifd** [comment]
Aha! damn... and your docs are so well written already... Apologies for not RTFM!

**Comment by jmcnamara** [comment]
> Apologies for not RTFM

Not your fault. There is a lot of documentation and it hard to find something like that that isn't a function. 🙂

**Comment by arifd** [comment]
Hi @jmcnamara, this was the code I was using to write the creation date (before I used the chrono feature and passed in the `Utc::now()` directly):

```rs
use chrono::Utc;
use rust_xlsxwriter::*;

fn main() -> Result<(), XlsxError> {
    let mut wb = Workbook::new();

    // This will produce a corrupted file:
    wb.set_properties(
        &DocProperties::new()
            .set_creation_datetime(&ExcelDateTime::from_timestamp(Utc::now().timestamp())?),
    );

    wb.save("corrupted.xlsx")?;

    Ok(())
}
```

And it would create a file that appeared to be corrupt according Micrsofot Excel for Mac:

![image (14)](https://github.com/user-attachments/assets/93022e2d-95d6-4922-98a3-e6f793154d92)

Does anything strike out to you as obviously wrong here?

The documentation for both functions in the conversion:

ExcelDateTime::from_timestamp:
```
Create a ExcelDateTime instance from a Unix time.

Create a ExcelDateTime instance from a [Unix Time](https://en.wikipedia.org/wiki/Unix_time) which is the number of seconds since the 1970-01-01 00:00:00 UTC epoch. This is a common format used for system times and timestamps.

Leap seconds are not taken into account.
```

DateTIme::timestamp:
```
Returns the number of non-leap seconds since January 1, 1970 0:00:00 UTC (aka “UNIX timestamp”).
```

**Comment by jmcnamara** [comment]
Thanks for the report. That is a  bug. I'll look into it.

In the meantime you may be able to work around it  by turning on the `rust_xlsxwriter` `chrono` feature and converting the `Utc::now()` to a `chrono::DateTime<Utc>` which will be accepted by `.set_creation_datetime()` (with the `chrono` flag on).

https://docs.rs/rust_xlsxwriter/latest/rust_xlsxwriter/trait.IntoCustomDateTimeUtc.html#impl-IntoCustomDateTimeUtc-for-%26DateTime%3CUtc%3E

**Comment by jmcnamara** [comment]
@arifd this is now fixed on main. Thanks for the report.
