### ISSUE TITLE
Bug: Header-only table produces invalid xlsx

### ISSUE THREAD

**Issue by matthias-stemmler** [jmcnamara/rust_xlsxwriter#110]
### Current behavior

When creating a table with header row and `first_row == last_row`, i.e. consisting only of the header row, Excel reports that the workbook is broken and had to be repaired. I tested it with Excel online, but I know it also happens in the desktop version. It works fine in LibreOffice.

### Expected behavior

The produced workbook should not be broken.

### Sample code to reproduce

```rust
use rust_xlsxwriter::{Table, Workbook, XlsxError};

fn main() -> Result<(), XlsxError> {
    let mut workbook = Workbook::new();
    let worksheet = workbook.add_worksheet();

    worksheet.add_table(0, 0, 0, 0, &Table::new())?;

    workbook.save("test.xlsx")?;
    Ok(())
}
```

### Environment

```text
- `rust_xlsxwriter` version: 0.75.0
- Cargo.toml dependency line for `rust_xlsxwriter`: rust_xlsxwriter = "0.75.0"
- rustc version: 1.80.1
- Excel version: Excel Online 16.0.18025.42301
```

**Comment by jmcnamara** [comment]
Thanks for the report. I'll look into it.

**Comment by jmcnamara** [comment]
I don't know if you are actually trying to create a table with 1 row or you are just reporting a bug you ran into.

If it is the first case then you can get a single row table by turning off the header:

```rust
use rust_xlsxwriter::{Table, Workbook, XlsxError};

fn main() -> Result<(), XlsxError> {
    let mut workbook = Workbook::new();
    let worksheet = workbook.add_worksheet();

    worksheet.add_table(0, 0, 0, 0, &Table::new().set_header_row(false))?;

    workbook.save("test.xlsx")?;
    Ok(())
}
```

If it is the second then it is a bug. It now raised an error:

```
Error: TableError("Table must have at least one row")
```

Fixed on main. Thanks for the report.

**Comment by matthias-stemmler** [comment]
Thanks for the quick reply! It was just an edge case I came across. I'll probably catch it and turn off the header in that case, as you suggested.
