### ISSUE TITLE
Chart Clone Operation Unclear

### ISSUE THREAD

**Issue by iUnknwn** [jmcnamara/rust_xlsxwriter#114]
### Current behavior

I would like to generate a chart on one sheet, and then insert another, smaller version of the same chart in another worksheet. 

Chart implements clone, so I assumed I could simply clone the chart and insert it into the other sheet. However, this doesn't appear to work. 

I know in the python version of xlsxwriter, [you cannot clone charts](https://github.com/jmcnamara/XlsxWriter/issues/184), and that each chart must be added with an `add_chart` call. 

If this is the case, perhaps this could be documented in the rust version? 

### Expected behavior

Chart clone should create another chart object, independent of the first object, that can be inserted on another worksheet. 

### Sample code to reproduce

```rust
let chart = make_chart(worksheet, global_config, 
  &sheet.chart, &datasets, limit_location)?;

let mut summary_chart = chart.clone();
summary_chart.set_height(400);
summary_chart.set_width(600);

let summary_offset_x = sheet_num % 3;
let summary_offset_y = sheet_num / 3;

let summary_sheet = workbook.worksheet_from_name("Summary")?;

// no chart is inserted on this page
summary_sheet.insert_chart_with_offset(0, 0, &summary_chart,
 (summary_offset_x * 600) as u32, 
 (summary_offset_y * 400) as u32)?;
```
```


### Environment

```text
- `rust_xlsxwriter` version: 0.79.0
- Cargo.toml dependency line for `rust_xlsxwriter`: `rust_xlsxwriter = "0.79.0"`
- rustc version: `rustc 1.74.1`
- Excel version: N/A
- OS: Windows 11
- If using wasm, which method/tool: N/A
```

**Comment by jmcnamara** [comment]
> Chart implements clone, so I assumed I could simply clone the chart and insert it into the other sheet. However, this doesn't appear to work.

It should work. Here is an example:

```rust
use rust_xlsxwriter::{Chart, ChartType, Workbook, XlsxError};

fn main() -> Result<(), XlsxError> {
    let mut workbook = Workbook::new();
    let worksheet = workbook.add_worksheet();

    // Add some test data for the charts.
    let data = [[1, 2, 3, 4, 5], [2, 4, 6, 8, 10], [3, 6, 9, 12, 15]];
    for (col_num, col_data) in data.iter().enumerate() {
        for (row_num, row_data) in col_data.iter().enumerate() {
            worksheet.write(row_num as u32, col_num as u16, *row_data)?;
        }
    }

    // Create a chart.
    let mut chart = Chart::new(ChartType::Column);
    chart.add_series().set_values("Sheet1!$A$1:$A$5");
    chart.add_series().set_values("Sheet1!$B$1:$B$5");
    chart.add_series().set_values("Sheet1!$C$1:$C$5");

    // Add the chart to the worksheet.
    worksheet.insert_chart(0, 4, &chart)?;

    // Clone and modify the chart.
    let mut chart = chart.clone();
    chart.set_height(400);
    chart.set_width(600);

    // Add a new worksheet.
    let worksheet = workbook.add_worksheet();

    // Add the chart to the worksheet.
    worksheet.insert_chart(0, 4, &chart)?;

    workbook.save("chart.xlsx")?;

    Ok(())
}
```

![screenshot 2](https://github.com/user-attachments/assets/53fccbdc-2efc-4b9f-998e-7056fd845a1c)

You can run this to confirm you get the same result.

**Comment by iUnknwn** [comment]
You're correct! My apologies. It looks like the problem is this line here where I try to insert the multiple charts into the same cell, each with a different offset.

```rust
// this is called as part of a for loop

let summary_offset_x = sheet_num % 3;
let summary_offset_y = sheet_num / 3;

summary_sheet.insert_chart_with_offset(0, 0, &summary_chart,
 (summary_offset_x * 600) as u32, 
 (summary_offset_y * 400) as u32)?;
```

If I shift that so that each chart is in its own cell, my code works fine. This works:

```rust
summary_sheet.insert_chart_with_offset(sheet_num as u32, 0, &summary_chart,
  (summary_offset_x * 600) as u32, 
  (summary_offset_y * 400) as u32)?;
```

Thank you for the help, and again I apologize for the error. 

Out of curiosity, if each cell can only have one chart, but I'd like charts nicely tiled, do you have any suggestions? My naive solution would be to format the column/row width and height, and then calculate the offsets based on those values, but

**Comment by jmcnamara** [comment]
> Just to confirm, I assume it's expected behavior that you can only insert one chart into one cell? I can tile the charts just by inserting them into adjacent cells and adjusting the column widths), but wanted to confirm that was normal.

Yes, it was mainly intended behaviour but on the other hand positioning charts (and other worksheet objects) relative to one cell is also a reasonable assumption from the end user. In fact the Python library allows it.

As such I've updated the library to support it. The changes are on main. You can test it by adding the GitHub repo to your `Cargo.toml` file:

```
cargo add --git https://github.com/jmcnamara/rust_xlsxwriter.git rust_xlsxwriter
```

Let me know how you get on. I'll need to make the same change (with tests) for other worksheet objects and then I'll roll it up into a release.

**Comment by iUnknwn** [comment]
That works perfectly! My code is inserting multiple offset charts in cell 0,0 and all are rendering nicely. Thank you so much!

**Comment by jmcnamara** [comment]
Thanks for testing and getting back to me. This is now available in crates.io as `rust_xlsxwriter v0.79.2`.
