### ISSUE TITLE
feature request: autofit with max width

### ISSUE THREAD

**Issue by StefanBRas** [jmcnamara/rust_xlsxwriter#119]
### Feature Request

I'm using autofit to set the width of some columns in a table. The data in these columns vary wildly and can sometimes be very long. I would like to use autofit with a max width, but that does not seem possible with the current implementation.

If I set the width beforehand, autofit will only change the width if the autofitted width is larger - which is the opposite of what I want.

Another way would be to set the width of each column to be `min(autofitted_width, SOME_MAX_WIDTH)` but it doesn't seem possible to get the current width of a column.

Thank you!

Edit: If you agree with the feature request and there's a implementation plan in place, I might be able to implement it myself

**Comment by jmcnamara** [comment]
Thanks for the suggestion. The auto fitting mechanism/APIs probably need some fine grained options. I'll need to think about that.

One potential solution that I had considered previously was to make public the cell sting width calculation function: https://github.com/jmcnamara/rust_xlsxwriter/blob/main/src/utility.rs#L772-L812

That would allow users to autofit themselves based on a subset of their data. Would something like that work for your use case?

**Comment by StefanBRas** [comment]
Yes, that would be perfect.

**Comment by jmcnamara** [comment]
I have added a `utility::autofit_cell_width()` function and `Worksheet::set_column_auto_width()` method to main to allow user defined versions of autofit. 

From the docs on `utility::autofit_cell_width()`:

Calculate the width required to auto-fit a string in a cell.

>The [`Worksheet::autofit()`](crate::Worksheet::autofit) method can be used to auto-fit
cell data to the optimal column width. However, in some cases you may wish to handle 
auto-fitting yourself and apply additional logic to limit the maximum and minimum ranges.
>
>The `autofit_cell_width()` function can be used to perform the required
calculation. It works by estimating the pixel width of a string based on the
width of each character. It also adds a 7 pixel padding for the cell
boundary in the same way that Excel does.
>
>You can use the  calculated width in conjunction with the
[`Worksheet::set_column_auto_width()`](crate::Worksheet::set_column_auto_width)
method, see the example below.
Notes:
>- The width calculation is based on the default Excel font type of Calibri
  and character size of 11. It will not give correct results for other fonts
  or font sizes.
>- If you are autofitting a header with an autofilter dropdown you should add
  an additional 6 pixels to account for the dropdown symbol.
>- When dealing with large data sets you can use `autofit_cell_width()` with
  just 50 or 100 rows of data as a performance optimization . This will
  produce a reasonably accurate autofit for the first visible page of data
  without incurring the performance penalty of calculating widths for
  thousands of non-visible strings.

Example:

```rust
use rust_xlsxwriter::{autofit_cell_width, Workbook, XlsxError};

fn main() -> Result<(), XlsxError> {
    let mut workbook = Workbook::new();

    // Add a worksheet to the workbook.
    let worksheet = workbook.add_worksheet();

    // Some string data to write.
    let cities = ["Addis Ababa", "Buenos Aires", "Cairo", "Dhaka"];

    // Write the strings:
    worksheet.write_column(0, 0, cities)?;

    // Find the maximum column width in pixels.
    let max_width = cities.iter().map(|s| autofit_cell_width(s)).max().unwrap();

    // Set the column width as if it was auto-fitted.
    worksheet.set_column_auto_width(0, max_width)?;

    workbook.save("worksheet.xlsx")?;

    Ok(())
}
```

Output:

![screenshot](https://github.com/user-attachments/assets/a393dfc4-3b1a-4f08-9cd7-b662a3813517)


You can test it by adding the GitHub repo to your `Cargo.toml` file:

```
cargo add --git https://github.com/jmcnamara/rust_xlsxwriter.git rust_xlsxwriter
```

Let me know how you get on.

**Comment by jmcnamara** [comment]
I've add these function to rust_xlsxwriter v0.80.0 with the names `utility::cell_autofit_width()` and `Worksheet::set_column_autofit_width()`.

**Comment by jmcnamara** [comment]
In v0.81.0 I added a new function `Worksheet::autofit_to_max_width()` to limit the upper bound of autofit:

```rust
    worksheet.write_string(0, 0, "This is some long text to test autofit")?;

    worksheet.autofit_to_max_width(200);
```

From the docs:

> Autofit the worksheet columns up to a maximum width.
>
> The `Worksheet::autofit()` method above simulates Excel's column
> autofit. On undesirable side-effect of this is that Excel autofits very
> long strings up to limit of 255 characters/1790 pixels. This is often
> too wide to display on a single screen at normal zoom. As such the
> `autofit_to_max_width()` method is provided to enable a smaller upper
> limit for autofitting long strings. A value of 300 pixels is recommended
> as a good compromise between column width and readability.
