### ISSUE TITLE
Don't depend on tempfile

### ISSUE THREAD

**Issue by jacobsvante** [jmcnamara/rust_xlsxwriter#12]
### Feature Request

As can be seen [here](https://github.com/jmcnamara/rust_xlsxwriter/blob/9082327c0aad6604ec91b142fcbd2684e09ec647/src/xmlwriter.rs#L28), rust_xlsxwriter currently depends on the tempfile crate, which in turn means that a `/tmp` directory (or equivalent) needs to be available. This isn't the case in Kubernetes environments by default, which is how I noticed this. I guess wasm environments would also have trouble with this.

Wouldn't it make more sense to default to in-memory storage, and make `tempfile` an optional feature to the crate? Then with that feature enabled, one could opt in to the file-creating behavior using an associated function, e.g. `Workbook::new_tempfile_backed()`.

**Comment by jmcnamara** [comment]
Thanks for the feedback.

> rust_xlsxwriter currently depends on the tempfile crate, which in turn means that a `/tmp` directory (or equivalent) needs to be available.

There are two items on the roadmap to deal with that:

* **In memory mode.** Which avoids tempfiles for systems that don't have them, and
* **Tempfile directory support.** Which allows you to specify a location other than "/tmp" as the temp directory.

The Python version supports both of those: https://xlsxwriter.readthedocs.io/workbook.html#constructor

However, I will need to balance this with a 'low-memory mode' feature (also supported in the Python version) where tempfile will be required as a backend for worksheets.

However, in the short term I may just remove the tempfile requirement (if there is no performance difference) and re-introduce it later as an optional feature for low-memory mode.

**Comment by jmcnamara** [comment]
I've pushed a version to main that removes the dependency on the tempfile crate. You can test it if you get a chance.

**Comment by jmcnamara** [comment]
Thanks for the suggestion.

Fixed in version 0.12.1. Closing.

**Comment by jacobsvante** [comment]
Great job! Thank you!!

**Comment by jacobsvante** [comment]
> However, I will need to balance this with a 'low/constant memory mode' feature (also supported in the Python version) where tempfile will be required as a backend for worksheets.

Agreed. Having this option will most likely be important for many scenarios, no matter how memory efficient Rust is.
