### ISSUE TITLE
Large memory consumption in constant memory mode

### ISSUE THREAD

**Issue by thibaltus** [jmcnamara/rust_xlsxwriter#120]
### Current behavior

Hello @jmcnamara 

First of all thanks to take time to maintain and improve this project ! 

I just want to let you known than i spotted an issues with current constant memory mode implementation. The memory consumption is not constant when writing worksheet to zip archive; this is mainly due to the fact than worksheet is [fully loaded in memory](https://github.com/jmcnamara/rust_xlsxwriter/blob/main/src/packager.rs#L448) just before writing it to archive.

We could simply read worksheet file in smaller slice to bypass this issues.
I'll be glad to open a pull request to implement a fix !

### Expected behavior

When using constant memory mode feature flag, memory consumption should be linear and not vary based on worksheet sizes.
 

### Sample code to reproduce

```rust
#!/usr/bin/env rust-script

//! cargo
//! [dependencies]
//! rust_xlsxwriter = { version = "0.79.4", features = ["constant_memory"] }
//! 
fn main() -> Result<(), rust_xlsxwriter::XlsxError> {
    let mut workbook = rust_xlsxwriter::Workbook::new();
    let worksheet = workbook.add_worksheet_with_constant_memory();
    for row in 0..600_000 {
        for col in 0..40 {
            // memory will remain constant when adding data to worksheet
            worksheet.write(row, col, "content")?;
        }
    }

    // memory footprint will increase when calling save()
    workbook.save("test.xlsx")?;

    Ok(())
}
```
```


### Environment

```text
- `rust_xlsxwriter` version: 0.79.4
- Cargo.toml dependency line for `rust_xlsxwriter`: { version = "0.79.4", default-features = false, features = ["constant_memory", "zlib"]}
- rustc version: 1.80.0
```

### Fix proposal

I fork your repos and come with a small fix, a simple update of ```packager.rs``` ```write_worksheet_file()``` function
```rust
#[cfg(feature = "constant_memory")]
{
    // Section 2. On disk cell data.
    // We also need to flush the last remaining row.
    worksheet.flush_last_row();

    worksheet.file_writer.rewind().unwrap();
    let mut reader = BufReader::new(worksheet.file_writer.get_ref());
    loop {
        let buffer = reader.fill_buf().unwrap();
        let length = buffer.len();
        if length == 0 {
            break;
        }
        self.zip.write_all(&buffer).unwrap();
        reader.consume(length);
    }
}
```

I've been using valgrind to monitor heap consumption (with upper sample code, 600 000 rows and 40 columns) :

With version 0.79.4, maximum heap footprint: 1.268 GB
With patch version 0.79.4, maximum heap footprint is 339.4 KB

**Comment by jmcnamara** [comment]
Thanks. That is a good catch. 

Please go ahead and submit a PR.

**Comment by jmcnamara** [comment]
> I've been using valgrind to monitor heap consumption (with upper sample code, 600 000 rows and 40 columns) :

For reference could you show a sample command line (or otherwise) that you used to do this?

**Comment by jmcnamara** [comment]
> To generate [heap profile](https://valgrind.org/docs/manual/ms-manual.html): `valgrind --massif-out-file ./valgrind --tool=massif ${binaryPath}`

Thank you. That is very useful.
