### ISSUE TITLE
Looking for feedback on rust_xlsxwriter error handling

### ISSUE THREAD

**Issue by jmcnamara** [jmcnamara/rust_xlsxwriter#14]
### Request for Feedback

Currently the `rust_xlsxwriter` error generation and handling is a bit restrictive. For background the error conditions are listed in the XlsxError docs: https://docs.rs/rust_xlsxwriter/latest/rust_xlsxwriter/enum.XlsxError.html

There are 2 levels of error that can affect an Excel file:

* Errors that would lead to a corrupt or broken file. Issues in that category would be merged ranges overlapping, which creates a corrupt-ish Excel file or File IO error or a ZipWriter errors. These would still need to be Results/Errors but could mainly be restricted to the `save()` methods.
* Non-corrupting errors that could be ignored with some data loss and a warning. Issues in this category would be row/column errors for out of bounds writing. For example it is a relative common issue that users try to write past Excel's row limit of ~ 1M rows. In these case the out of bounds writes could be raised as a STDERR warning but a valid file would still be produced. This is how the Python/C/Perl versions of the library work. Python also has exception handling but that isn't available in Rust.

I am looking for feedback from people using the library on their experience with the APIs and error handling.

**Comment by jmbrunskill** [comment]
I've only just started using this library, and haven't got experience with the C, or Python versions of the library.
However, in general I support returning errors for dataloss situations. I think rust programmers generally expect robustness and would rather know the constraints and allow accurate reporting of data issues etc.

I can see the use case for still being able to create a valid file even with some dataloss though.

As inspiration, you could have a look at what chrono has done?
They have two versions of a lot of functions one that returns an option and one that just panics (they're actually in the process of phase this out but still...)

https://docs.rs/chrono/latest/chrono/naive/struct.NaiveDate.html#method.from_ymd
https://docs.rs/chrono/latest/chrono/naive/struct.NaiveDate.html#method.from_ymd_opt

You could potentially do something similar with something like `write_data_lossy` which would not return and error, and have another version of the function `write_data` that does return an error?

**Comment by jmcnamara** [comment]
@jmbrunskill thanks for the feedback and suggestions.
