### ISSUE TITLE
Support for custom paths

### ISSUE THREAD

**Issue by songlinshu** [jmcnamara/rust_xlsxwriter#17]
### Feature Request

How do I set the save path?
 c:\aa\cell_formats.xlsx
workbook.save("c:\aa\cell_formats.xlsx")?;

**Comment by jmcnamara** [comment]
This is a general issue when working with Windows paths. The problem here is that `\a` and `\c` are control character in Rust/ASCII so you can't use them in a string.

```
error: unknown character escape: `a`
 --> src\main.rs:8:23
  |
8 |     workbook.save("c:\aa\cell_formats.xlsx")?;
  |                       ^ unknown character escape
  |
```

You can either use forward slashes:

```rust
   workbook.save("c:/aa/cell_formats.xlsx")?;
```

Or escape the escapes:


```rust
    workbook.save("c:\\aa\\cell_formats.xlsx")?;
```

**Comment by songlinshu** [comment]
Thank !
