### ISSUE TITLE
Bug: Several clippy::pedantic warnings

### ISSUE THREAD

**Issue by adriandelgado** [jmcnamara/rust_xlsxwriter#21]
### Current behavior

Running `cargo clippy -- -W clippy::pedantic` shows hundreds of warnings, most of them are easily fixable.

### Expected behavior

`cargo clippy -- -W clippy::pedantic` shouldn't give any results

### Sample code to reproduce

```markdown
cargo clippy -- -W clippy::pedantic
```

### Environment

```markdown
- rust_xlsxwriter version: 0.32.0
- rustc version: 1.68.2
- Excel version:
- OS: Linux (Pop os)
```

### Any other information

I will send a PR in a couple of minutes.

**Comment by jmcnamara** [comment]
> I will send a PR in a couple of minutes.

Please don’t. 

I’ve run Pedantic in the past and it suggestions are often contradictory or not useful. 

You may have noticed that I already run clippy locally and as part of the CI. 

I’ll rerun clippy with Pendantic again to see if it has any genuine issues but I don’t think a bulk fix PR will be helpful.

**Comment by adriandelgado** [comment]
> > I will send a PR in a couple of minutes.
> 
> Please don’t.
> 
> I appreciate the intention but I’ve run Pedantic in the past and its suggestions are often contradictory or not useful.
> 
> You may have noticed that I already run clippy locally and as part of the CI.
> 
> I’ll rerun clippy with Pedantic again to see if it has any genuine issues but I don’t think a bulk fix PR will be helpful.

I just read this comment, sorry :( 
I've send the PR, but feel free to suggest any changes, no hard feelings. I understand what you are saying about Pedantic. I manually inspected the changes to my liking but It's your repo after all.

**Comment by jmcnamara** [comment]
I ran clippy with `clippy::pedantic` and fixed the main issues it flagged. Thanks for the prompt. 

Closing.
