### ISSUE TITLE
RFC: moving the minimum required version of Rust to 1.70.0 by end of 2023

### ISSUE THREAD

**Issue by adriandelgado** [jmcnamara/rust_xlsxwriter#24]
If everything goes well `OnceCell` is going to land on Rust 1.70 (June 1st). See: https://github.com/rust-lang/rust/pull/105587

It's always nice to get rid of a dependency.

**Comment by jmcnamara** [comment]
> It's always nice to get rid of a dependency.

Agreed. This will need to wait until Rust 1.70, right?

**Comment by adriandelgado** [comment]
> Agreed. This will need to wait until Rust 1.70, right?

Yep. I don't know if you have a [MSRV](https://doc.rust-lang.org/cargo/reference/manifest.html?highlight=minimal#the-rust-version-field). I would suggest not to have it since this crate is in rapid/frequent development and changes.

**Comment by jmcnamara** [comment]
> Yep. I don't know if you have a [MSRV](https://doc.rust-lang.org/cargo/reference/manifest.html?highlight=minimal#the-rust-version-field).

I don't. If this has a hard requirement on Rust 1.70 then I'm probably going to pass on this change for a year or more.

I'll close it for now.

**Comment by jmcnamara** [comment]
Reopening this since Rust v1.70 is out. I'm looking for opinions on whether people would any concerns about having v170 as a MSRV for `rust_xlsxwriter` in order to drop a dependency. The current implicit MSRV is v1.68.2.

**Comment by jmcnamara** [comment]
Closing again. The MSRV of `rust_xlsxwriter` will depend on the MSRV of Polars if it is eventually integrated for xlsx generation.

**Comment by jmcnamara** [comment]
Just to note that I had to push the MSRV to v1.73.0 to pick up the latest 2.x versions of zip.rs which includes a fix required by `rust_xlsxwriter`. As a result of that I also replaced `lazy_static` with `std::cell::OnceCell`.

This will be upstreamed soon in `rust_xlsxwriter` v0.67.0.

**Comment by adriandelgado** [comment]
I left some comments on the commit in question. Please check them out before releasing v0.67.0.

**Comment by jmcnamara** [comment]
@adriandelgado Thanks for the input. When you get a chance can you have a look at the revised (and rebased) change on main.
