### ISSUE TITLE
Set the Worksheet name before adding it to the Workbook

### ISSUE THREAD

**Issue by claudiofsr** [jmcnamara/rust_xlsxwriter#33]
### Feature Request

It is possible something like that:

      let mut worksheet = Worksheet::new();
      worksheet.set_name("Name XYZ")?;
or

      let worksheet = Worksheet::new("Name XYZ");

And then:

      workbook.push_worksheet(worksheet);

I don not want to use:

      let _worksheet3 = workbook.add_worksheet().set_name("Data");

I would like to create multiple worksheets with previous names:

     let mut worksheets: Vec<Worksheet> = Vec::new();

     // Split a vector into smaller vectors of size N
     vector.chunks(SPLIT_NUMBER).enumerate.for_each(|(index, data)| {
        let name = format("Name {}", index);
        let worksheet = Worksheet::new(name);
        ...
        worksheets.push(worksheet);
     });

     ...

     worksheets.for_each(|worksheet| {
        workbook.push_worksheet(worksheet);
     }

Thanks!

**Comment by claudiofsr** [comment]
Perfect!
Thank you very much.
Sorry for disturbing!

**Comment by jmcnamara** [comment]
No problem. 🙂

**Comment by jmcnamara** [comment]
I'm going to clean up/remove the similar question on the roadmap just to keep the discussion cleaner and more roadmap focused.
