### ISSUE TITLE
`impl IntoExcelData for String` (and optionally `&String`)

### ISSUE THREAD

**Issue by LeoniePhiline** [jmcnamara/rust_xlsxwriter#35]
### Feature Request

Examples:

```rust
                // Assume `path: PathBuf`
                worksheet.write(
                    0,
                    0,
                    path.display().to_string(),
                )?;

                worksheet.write(
                    0,
                    0,
                    format!("Something {formatted:#?}"),
                )?;
```

-> "the trait `IntoExcelData` is not implemented for `std::string::String`"

Must work around with `&*` (as `impl IntoExcelData for &str` is the only stringy type available), which is quite cumbersome.

https://docs.rs/rust_xlsxwriter/latest/rust_xlsxwriter/trait.IntoExcelData.html#foreign-impls

**Comment by jmcnamara** [comment]
There should be a `IntoExcelData impl` for `&String`. That was an omission and I'll fix that.

However, there aren't any `write*()` APIs (or other APIs) in rust_xlsxwriter that take `String` so I will leave that one out.

**Comment by jmcnamara** [comment]
Added to main.

**Comment by LeoniePhiline** [comment]
Awesome, thank you! 🤍

**Comment by jmcnamara** [comment]
For APIs that take a string-like object I thought that `&str` would be the best option and there is a certain amount of consensus around that usage in Rust APIs.

However `impl Into<String>` is more generic in that it also allows `String` in addition to `&str` and `&String`. In addition, in almost all cases the rust_xlsxwriter library takes an owned copy of the string so `impl Into<String>` is a better fit for that case too.

@adriandelgado could I get a second opinion from you on the use of `impl Into<String>` versus `&str` in the APIs.

**Comment by jmcnamara** [comment]
> This is not entirely accurate.

I meant it was more generic than `&str`. Your other points I agree with.

**Comment by jmcnamara** [comment]
I've converted `write_string()` from `&str` to `impl Into<String>` on main and I've extended `write()` to support `&str`, `&String`, `String`, and `Cow<'_, str>`.

It is probably slightly slower (<1%) but within the measurable bounds so that is probably acceptable/ignorable for the added genericism.

**Comment by LeoniePhiline** [comment]
Lgtm!

To reduce compile times due to monomorphization, you can additionally use this technique:

In the generic function, only call `.into()` on the generic argument. 

Then, use the resulting `String` as argument for calling a non-generic function that only accepts `String`. 

The latter, non-generic function then contains the rest of the business logic and requires no monomorphization. 

The generic function on the other hand remains minimal in size and thus fast to compile for multiple concrete types.

**Comment by jmcnamara** [comment]
> To reduce compile times due to monomorphization, you can additionally use this technique:

Thanks. Done.

**Comment by jmcnamara** [comment]
These changes have been rolled up into v0.37.0. Thanks for the input.

**Comment by adriandelgado** [comment]
Sorry I didn't respond, I was on vacation at that time and I just checked my notifications.

I think the suggestions from @LeoniePhiline are accurate. In general, if a function needs an owned string its better that the caller of the function is the one making the allocations. If a function takes only a `&str` it usually means the function doesn't need to allocate internally. In general, its idiomatic to be explicit about what the function needs.

Checkout the API guidelines: [C-CALLER-CONTROL](https://rust-lang.github.io/api-guidelines/flexibility.html#caller-decides-where-to-copy-and-place-data-c-caller-control)

**Comment by adriandelgado** [comment]
If you were creating a new crate from scratch, then I would insist that you follow the Rust API guidelines to keep it consistent and idiomatic. However, the way it is right now doesn't seem like a big deal so its your call if you want to change it.

**Comment by LeoniePhiline** [comment]
There was considerable investment into this crate's performance.

The performance at the api boundaries might not have been part of these measurements and improvements.

I could imagine that there is a lot to gain by accepting allocated strings and preventing unnecessary clones. 

Accepting `Into<String>` could allow strings to be passed while not breaking backwards compatibility with existing `&str` users.

I think this is a good idea, with focus on the APIs with the most bytes throughput in common crate usage.

**Comment by LeoniePhiline** [comment]
PS: People might be very willing to help. Just create “good first issue”s for the tasks. :)

**Comment by jmcnamara** [comment]
Let's continue this discussion in #16 "Proposal: generic `write()` method"
