### ISSUE TITLE
feature request: split `set_align` into `set_horizontal_align` and `set_vertical_align`

### ISSUE THREAD

**Issue by Chronophylos** [jmcnamara/rust_xlsxwriter#4]
### Feature Request

Splitting the `Format::set_align` function into `set_horizontal_align` and `set_vertical_align` is easier to read as it is clear which alignment is set. `XlsxAlign` would also need to be spit into `HorizontalAlign` and `VerticalAlign`.

**Comment by jmcnamara** [comment]
Thanks for the suggestion. 

This one I probably won't add. The `set_align()` method is similar to the same method/function in the Python/C/Perl versions and most folks seem to be able to navigate that without any problems.
