### ISSUE TITLE
feature request: impl IntoExcelData for bool

### ISSUE THREAD

**Issue by Christoph-AK** [jmcnamara/rust_xlsxwriter#40]
### Feature Request

Hi and thanks for the crate!

I'm currently writing an sql export tool from MSSQL to xlsx. 

I would love to be able to write bools directly with `sheet.write(row, col, true)`.

Excel should have some kind of representation for logic, maybe just the text TRUE and FALSE, but potentially some better values or cell types.

**Comment by jmcnamara** [comment]
> I would love to be able to write bools directly with `sheet.write(row, col, true)`.

I 100% meant to do that but somehow forgot. I've pushed an update to main with support added.

> Excel should have some kind of representation for logic, maybe just the text TRUE and FALSE, but potentially some better values or cell types.

It has a boolean `TRUE/FALSE` type which can be written with `worksheet.write_boolean()` ([link](https://docs.rs/rust_xlsxwriter/latest/rust_xlsxwriter/struct.Worksheet.html#method.write_boolean)) and now `write()`.

Thanks for the prompt.

**Comment by jmcnamara** [comment]
Example:

```rust
use rust_xlsxwriter::{Workbook, XlsxError};

fn main() -> Result<(), XlsxError> {
    let mut workbook = Workbook::new();

    // Add a worksheet to the workbook.
    let worksheet = workbook.add_worksheet();

    worksheet.write(0, 0, true)?;
    worksheet.write(1, 0, false)?;

    workbook.save("worksheet.xlsx")?;

    Ok(())
}
```

Output:

![screenshot](https://github.com/jmcnamara/rust_xlsxwriter/assets/94267/11cbf3f0-fcbb-4416-92eb-b24491a6d6d7)

**Comment by Christoph-AK** [comment]
Perfect, thank you so much!
