### ISSUE TITLE
Possible bug with sheet name apostrophes in ChartRange

### ISSUE THREAD

**Issue by 2ndDerivative** [jmcnamara/rust_xlsxwriter#44]
### Current behavior

"'" is only stripped from sheet name in ChartRange if both start and beginning are apostrophes

### Expected behavior

Either ' in the beginning or the end of the sheet name in a Chart range would be stripped, since the excel standard requires them to be removed independently

### Sample code to reproduce

```markdown
use rust_xlsxwriter::{Workbook, XlsxError};

fn main() -> Result<(), XlsxError> {
    // This apostrophe would not be stripped since the code only strips if both end and beginning
    // of the chart name are apostrophes
    let chart = ChartRange::new_from_string("\'SheetName!A1:B2");
}
```

### Environment

```markdown
- rust_xlsxwriter version:
- rustc version:
- Excel version:
- OS:
```

**Comment by jmcnamara** [comment]
Thanks for the detailed report.

As reported this isn't a bug since it isn't intended that the apostrophes are stripped in general. They are only removed when they are "notional", i.e., when they indicate the sheet name contains whitespace.

There probably does need to be centralised name checking, like you suggested in #45. I'll look into that.

I also need to check if there is a bug if an invalid worksheet name is passed as a chart range. I'll keep this open and look into that.

Thanks again.

**Comment by jmcnamara** [comment]
> According to the Microsoft spec it's not supposed to use apostrophes in general if I read this right

Correct but `rust_xlsxwriter` doesn't sanitize the input (in this case). This would be considered a user input error and should raise a validation error.

However, I just checked and it doesn't:

```rust
use rust_xlsxwriter::{Chart, ChartType, Workbook, XlsxError};

fn main() -> Result<(), XlsxError> {
    let mut workbook = Workbook::new();
    let worksheet = workbook.add_worksheet();

    let data = [1, 2, 3, 2, 1];
    worksheet.write_column(0, 0, data)?;

    let mut chart = Chart::new(ChartType::Column);
    chart.add_series().set_values("'Sheet1!$A$1:$A$5");
    worksheet.insert_chart(0, 2, &chart)?;

    workbook.save("chart.xlsx")?;

    Ok(())
}
```

```bash
$ cargo run --example gh44    # No error.
```

So I'll look into that and fix it so that there is proper validation.

**Comment by 2ndDerivative** [comment]
That makes sense. So it would get plugged into the central system I suggested, that would be more idiomatic.

**Comment by jmcnamara** [comment]
Closing this and merging the issue with #45
