### ISSUE TITLE
feature request: freeze panes

### ISSUE THREAD

**Issue by jacobsvante** [jmcnamara/rust_xlsxwriter#5]
### Feature Request

Thank you for doing this epic rewrite! GJ so far!

I miss `freeze_panes` from the python version. (I.e. https://github.com/jmcnamara/XlsxWriter/blob/d3050b2d0f6a63415694d186094edbb2ce349279/xlsxwriter/worksheet.py#L3393)

Can't see the feature in your roadmap so I thought I'd add an issue for it.

**Comment by jmcnamara** [comment]
Thanks for the comments.

I've added Freeze Panes (https://xlsxwriter.readthedocs.io/worksheet.html#worksheet-freeze-panes) to the roadmap and I'll add it to rust_xlsxwriter soon.

**Comment by jacobsvante** [comment]
Wihoo! Thank you!

**Comment by jmcnamara** [comment]
I've added this feature to main. See also the [app_panes] example application.

Try it out and let me know how you get on.

[app_panes]: https://rustxlsxwriter.github.io/examples/panes.html

**Comment by jacobsvante** [comment]
Works great, thank you for this! 😀

**Comment by jmcnamara** [comment]
This is now available in version v0.10.0: https://rustxlsxwriter.github.io/changelog.html

Best regards.

**Comment by jacobsvante** [comment]
Woop woop!
