### ISSUE TITLE
feature request: Implement `IntoExcelData` for `serde_json::Value`

### ISSUE THREAD

**Issue by Xydez** [jmcnamara/rust_xlsxwriter#50]
### Feature Request

It would be pretty nice to be able to do `sheet.write(serde_json::Value)`, pretty what needs to be done is just implement for all types of `serde_json::Value`. Should perhaps be put behind a feature flag.

Or even better, maybe `IntoExcelData` could even be implemented for anything that derives `Serialize`, or maybe a macro

**Comment by jmcnamara** [comment]
Thanks. That is a good suggestion. I'll look into it.

**Comment by jmcnamara** [comment]
Closing in favour of #61
