### ISSUE TITLE
question: Vec<CustomStruct> for headers and data?

### ISSUE THREAD

**Issue by cchance27** [jmcnamara/rust_xlsxwriter#54]
### Question

Is there a way to serialize a vec<customstruct> to a xlsx data table? I was looking through the documentation but it seems only to be possible from arrays and things that are iters, I imagine there should be a way to serialize a vec<customstruct> into a table but it's evading me.

**Comment by jmcnamara** [comment]
> Is there a way to serialize a vec to a xlsx data table?

Could you give an example of a data structure you want to serialize. Also when you say "data table" do you mean a worksheet or a worksheet [table](https://docs.rs/rust_xlsxwriter/latest/rust_xlsxwriter/struct.Table.html).

**Comment by cchance27** [comment]
Basically just a ‘’’struct example { Column1: size,Column2: usize}Let data = Vec![example { Column1: 0, Column:2 }, example { Column1: 3, Column:4}];‘’’Basically a way to turn the above data into an excel worksheet with first row headers Column1, Column2… followed by data rowsPardon my reply being poorly formatted responding from mail on my phone.On Sep 9, 2023, at 7:36 PM, John McNamara ***@***.***> wrote:﻿

Is there a way to serialize a vec to a xlsx data table?

Could you give an example of a data structure you want to serialize. Also when you say "data table" do you mean a worksheet or a worksheet table.

**Comment by jmcnamara** [comment]
Thanks. 

Would serde style serialization meet you needs? I'm probably going to implement that as the net major feature. See also #50

**Comment by jmcnamara** [comment]
Closing this because it will probably be covered by #50, when complete.
