### ISSUE TITLE
feature request: Could serialize_chrono_naive_to_excel() accept Option<T>?

### ISSUE THREAD

**Issue by claudiofsr** [jmcnamara/rust_xlsxwriter#62]
### Feature Request

Hi!!!

Please see:
https://github.com/claudiofsr/read_xml/blob/master/src/excel.rs
https://github.com/claudiofsr/read_xml/blob/master/src/xml_structs/efinanceira.rs

I have:

```
#[derive(Debug, Default, Serialize, Deserialize, Clone)]
pub struct InfoEFinanceira {
   ...
    #[serde(rename = "Ano/Mês Caixa Reportado")]
    pub ano_mes_caixa: Option<NaiveDate>,
   ...
    #[serde(rename = "Balanço da Conta: Total de Débitos")]
    pub tot_debitos: f64,
}
```
I try use
```
#[serde(rename = "Ano/Mês Caixa Reportado", serialize_with = "serialize_chrono_naive_to_excel")]
```
but I have `ano_mes_caixa: Option<NaiveDate>`.

Could serialize_chrono_naive_to_excel() accept `Option<T>`?

Thanks.

**Comment by jmcnamara** [comment]
> Could serialize_chrono_naive_to_excel() accept `Option<T>`?

Yes. Or at least I can add a second function to do `Option<T>`. Would that work for you?

**Comment by claudiofsr** [comment]
Both possibilities are good!

Thanks.

**Comment by jmcnamara** [comment]
> Both possibilities are good!

I may implement both  but as a first pass I implemented the second option and added a `serialize_chrono_option_naive_to_excel` function.  

Can you try that in your use case and let me know how you get on.

**Comment by claudiofsr** [comment]
I tested it with my data and `serialize_chrono_option_naive_to_excel` worked perfectly. 

Thanks!!!

**Comment by jmcnamara** [comment]
This is upstream in Cargo in v0.53.0. Thanks for the suggestion and testing.
