### ISSUE TITLE
feature request: please add support for `Result<T, E>` to `IntoExcelData`

### ISSUE THREAD

**Issue by lucatrv** [jmcnamara/rust_xlsxwriter#64]
### Feature Request

Currently `IntoExcelData` supports `Option<T>`, which can be used when a value maybe present or not. However often when dealing with tabular data we need to define fallback types, for instance a column could normally contain an `f64` but may sometimes contain a `String`. I think the best way to deal with this very common occurrence is to use `Result<f64, String>`. Of course also other use cases can be envisioned for a `Result<T, E>` type.
The `rust_xlsxwriter::Worksheet::write*` methods should correctly write `Result<T, E>` if both `T` and `E` are supported types.

**Comment by jmcnamara** [comment]
I'm not, at first glance, convinced of the general utility of this.

However, I'll consider it and if anyone else thinks this would be useful then a +1 or "me too" comment will help persuade me.

**Comment by lucatrv** [comment]
I add references to related discussions for [rust-csv](https://github.com/BurntSushi/rust-csv/issues/345) and [calamine](https://github.com/tafia/calamine/issues/339#issuecomment-1863555597).

**Comment by jmcnamara** [comment]
Ok. It seems like you have a plan you are working to. 

I've added this to main. Let me know how you get on.

It is undocumented for now. I'll add that later.

**Comment by lucatrv** [comment]
Thanks @jmcnamara , yes I will let you know if this feature can be added to `rust-csv` and `calamine`, as it will ease management of invalid field formats.

**Comment by jmcnamara** [comment]
This feature has been pushed to crates.io in `rust_xlsxwriter` v0.60.0.
