### ISSUE TITLE
feature request: `Worksheet` and `SerializeFieldOptions` / `CustomSerializeField` methods should take the same format type

### ISSUE THREAD

**Issue by lucatrv** [jmcnamara/rust_xlsxwriter#67]
### Feature Request

`Worksheet::*_format` methods take a `&Format`, while `SerializeFieldOptions::*_format` and `CustomSerializeField::*_format` methods take a generic `impl Into<Format>`. @jmcnamara I report this for your reference, not because it is a bug, but because maybe you would like them to be aligned.

Just to make an example, the following code compiles:

```rust
static CENTER_FORMAT: LazyLock<Format> = LazyLock::new(|| {
    Format::new().set_align(rust_xlsxwriter::FormatAlign::Center)
});
worksheet.set_column_format(0, &CENTER_FORMAT)?;
```

while the following code does not compile:

```rust
static CENTER_FORMAT: LazyLock<Format> = LazyLock::new(|| {
    Format::new().set_align(rust_xlsxwriter::FormatAlign::Center)
});
let header_options = rust_xlsxwriter::SerializeFieldOptions::new()
        .set_header_format(&CENTER_FORMAT);
```

and should be written as:

```rust
static CENTER_FORMAT: LazyLock<Format> = LazyLock::new(|| {
    Format::new().set_align(rust_xlsxwriter::FormatAlign::Center)
});
let header_options = rust_xlsxwriter::SerializeFieldOptions::new()
        .set_header_format(&*CENTER_FORMAT);
```

**Comment by jmcnamara** [comment]
> maybe you would like them to be aligned.

I would, but I would align them around `format: impl Into<Format>` and not `format: &Format`.

The From/Into allows the user to create a format from a number format string like this:

```rust
    let header_options = SerializeFieldOptions::new()
        .set_custom_headers(&[CustomSerializeField::new("cost").set_value_format("$0.00")]);

    // As opposed to:
    let value_format = Format::new().set_num_format("$0.00");

    let header_options = SerializeFieldOptions::new()
        .set_custom_headers(&[CustomSerializeField::new("cost").set_value_format(&value_format)]);

```

That is more useful for some of the secondary components that only require a number format `Format`.  That isn't as useful for the `worksheet()` methods which is why (I think) I didn't do it initially.

**Comment by lucatrv** [comment]
Yes I agree
