### ISSUE TITLE
Bug: issue with serde `skip_serializing_if`

### ISSUE THREAD

**Issue by jmcnamara** [jmcnamara/rust_xlsxwriter#71]
### Current behavior

When using `skip_serializing_if` on a field the output can become unaligned.

### Expected behavior

Skipping a value should maintain the correct incrementatal row number.

### Sample code to reproduce

```rust
use rust_xlsxwriter::{ExcelSerialize, Format, Workbook, XlsxError};
use serde::Serialize;

fn main() -> Result<(), XlsxError> {
    let mut workbook = Workbook::new();

    // Add a worksheet to the workbook.
    let worksheet = workbook.add_worksheet();

    fn skip_check(value: &str) -> bool {
        value == "Peach"
    }

    //use rust_xlsxwriter::Format;
    let _foo = Format::new().set_bold();

    #[derive(ExcelSerialize, Serialize)]

    struct Produce {
        #[serde(skip_serializing_if = "skip_check")]
        fruit1: &'static str,

        fruit2: &'static str,
    }

    // Create some data instances.
    let items = [
        Produce {
            fruit1: "Peach",
            fruit2: "= Peach?",
        },
        Produce {
            fruit1: "Plum",
            fruit2: "= Plum?",
        },
        Produce {
            fruit1: "Pear",
            fruit2: "= Pear?",
        },
    ];

    worksheet.set_serialize_headers::<Produce>(0, 0)?;
    worksheet.serialize(&items)?;

    // Save the file.
    workbook.save("serialize.xlsx")?;

    Ok(())
}
```

![screenshot](https://github.com/jmcnamara/rust_xlsxwriter/assets/94267/0c74e820-1e48-4c6f-a005-f684b5749e36)

Note, fixing this may break serialization of array **values** in a struct. That probably isn't a common use case though.

**Comment by zjp-CN** [comment]
IIUC `skip_serializing_if` on one field here basically means to skip serialization of the row containg other fields given a condition. 

So the caller can do it directly by iterator filter or continuing in the loop

```rust
let slice: &[Produce] = ...;
slice.iter().filter(|p| !skip_check(&p.fruit1)).try_for_each(|p| worksheet.serialize(p));
```

**Comment by zjp-CN** [comment]
Oh, I just realized the problem is not that callers can't make it, instead it's if they use `skip_serializing_if`, the outcome is incorrect 😢

**Comment by jmcnamara** [comment]
> it's if they use `skip_serializing_if`, the outcome is incorrect 😢

Yes. That is it. ☺️
