### ISSUE TITLE
Is it possible to add a custom XlsxError

### ISSUE THREAD

**Issue by han1548772930** [jmcnamara/rust_xlsxwriter#72]
### Feature Request

XlsxError::form_str("custom XlsxError")

**Comment by jmcnamara** [comment]
Hi,

That is a good suggestion. I'll add that.

It would look something like this:

```rust
use rust_xlsxwriter::XlsxError;

fn main() -> Result<(), XlsxError> {
    Err(XlsxError:: CustomError("Some custom error message".to_string()))
}
```

With output:

```
Error: CustomError("Some custom error message")
```


Is that what you are looking for?

**Comment by han1548772930** [comment]
Yes this looks great thank you

**Comment by jmcnamara** [comment]
I've added a `XlsxError::CustomError(String)` enum to main. It will be in the next release (v0.61.0).

**Comment by jmcnamara** [comment]
This is now upstream in the v0.61.0 crate.
