### ISSUE TITLE
Is it possible for us to add comments to cells?

### ISSUE THREAD

**Issue by Huang-Hong** [jmcnamara/rust_xlsxwriter#79]
### Question

Is it possible for us to add comments to cells? It seems that the relevant function can not be found
![image](https://github.com/jmcnamara/rust_xlsxwriter/assets/32867672/db0c88cb-9a84-4250-a206-09a42d71b211)

**Comment by jmcnamara** [comment]
Not currently. It is a planned feature, on the Roadmap, since this feature is supported in the Python version: https://xlsxwriter.readthedocs.io/working_with_cell_comments.html

**Comment by Huang-Hong** [comment]
ok，thanks

**Comment by Huang-Hong** [comment]
> > Is it possible for us to add comments to cells
> 
> Not currently. It is a planned feature, on the Roadmap, since this feature is supported in the Python version: https://xlsxwriter.readthedocs.io/working_with_cell_comments.html

got it，thanks

**Comment by jmcnamara** [comment]
Closing this as a duplicate of the Roadmap item for "Cell Comments" in #1
