### ISSUE TITLE
Feature request: utility::validate_sheetname visibility

### ISSUE THREAD

**Issue by barsa-net** [jmcnamara/rust_xlsxwriter#83]
### Question

Currently [utility::validate_sheetname](https://github.com/jmcnamara/rust_xlsxwriter/blob/0351b2f3d65df703f545d8da6cd0492ee99a6d5d/src/utility.rs#L411) visibility is set as `pub(crate)`, would it be possible in a future release to make it just `pub`?

I ask this because in my current use case I would like to check a sheet name validity before using `set_name()` without the need to reimplement the same logic of `validate_sheetname()`.

**Comment by jmcnamara** [comment]
> would it be possible in a future release to make it just `pub`?

Sure. I can do that. I'll just need to change the error handling around a bit. I'll add it in the next release.

**Comment by jmcnamara** [comment]
I've added a public `utility::check_sheet_name()` function to main.

Example:

```rust

use rust_xlsxwriter::{utility, XlsxError};

fn main() -> Result<(), XlsxError> {
    // This worksheet name is valid.
    utility::check_sheet_name("2030-01-01")?;

    // This worksheet name isn't valid due to the forward slashes.
    utility::check_sheet_name("2030/01/01")?;

    Ok(())
}
```

Output:

```bash
$ cargo run --example doc_utility_check_sheet_name
    Finished dev [unoptimized + debuginfo] target(s) in 0.17s
     Running `target/debug/examples/doc_utility_check_sheet_name`

Error: SheetnameContainsInvalidCharacter("Invalid Excel worksheet name '2030/01/01'")
```

Let me know if that works for you.

**Comment by barsa-net** [comment]
That works perfectly, thanks!

**Comment by jmcnamara** [comment]
Thanks for testing. I will close the request. I will be in the next release.

**Comment by jmcnamara** [comment]
This is now upstream in v0.63.0. Thanks for the input.
